os: linux
dist: focal

language: python
python:
  - '3.8'

branches:
  only:
    - master

services:
  - docker

before_install:
  - chmod +x ./travis/build_and_test.sh

script:
  - ./travis/build_and_test.sh


